services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: africanmedicalreviewui
    ports:
      - "8011:80"
    networks:
      - nesssery

networks:
  nesssery:
    name: nesssery
    external: true