services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: africanmedicalreviewui
    ports:
      - 8012:8012 
    networks:
      - nesssery

networks:
  nesssery:
    name: nesssery
    external: true