name: africanmedicalreview
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
    
  flutter_hooks: ^0.20.5
  get: ^4.7.2
  http: ^0.13.5
  get_storage: ^2.1.1
  file_picker: ^5.3.3
  url_launcher: ^6.1.14
  font_awesome_flutter: ^10.6.0
  google_fonts: ^4.0.4
  cached_network_image: ^3.3.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
      - assets/images/image-desktop-header.jpg
